export = TsUtil;
declare class TsUtil {
    reset(): void;
    original_network_id: any;
    transport_stream_id: any;
    service_ids: {};
    transport_streams: Map<any, any>;
    services: Map<any, any>;
    epg: TsEpg;
    time: Date;
    download_data_ids: Map<any, any>;
    download_ids: Map<any, any>;
    logo_ids: Map<any, any>;
    logo_id_refs: Map<any, any>;
    versions: {
        pat: Map<any, any>;
        cat: Map<any, any>;
        pmt: Map<any, any>;
        dsmcc: Map<any, any>;
        nit: Map<any, any>;
        sdt: Map<any, any>;
        bat: Map<any, any>;
        sdtt: Map<any, any>;
        cdt: Map<any, any>;
    };
    addPat(pid: any, objPat: any): boolean;
    addCat(pid: any, objCat: any): boolean;
    addPmt(pid: any, objPmt: any): boolean;
    addDsmcc(pid: any, objDsmcc: any): boolean;
    addNit(pid: any, objNit: any): boolean;
    addSdt(pid: any, objSdt: any): boolean;
    addBat(pid: any, objBat: any): boolean;
    addEit(pid: any, objEit: any): boolean;
    addTdt(pid: any, objTdt: any): boolean;
    addTot(pid: any, objTot: any): boolean;
    addSdtt(pid: any, objSdtt: any): boolean;
    addCdt(pid: any, objCdt: any): boolean;
    hasTransportStreams(onid: any): boolean;
    hasServices(onid: any, tsid: any): boolean;
    hasOriginalNetworkId(): boolean;
    hasTransportStreamId(): boolean;
    hasServiceIds(): boolean;
    hasPresent(onid: any, tsid: any, sid: any): boolean;
    hasFollowing(onid: any, tsid: any, sid: any): boolean;
    hasSchedule(): boolean;
    hasTime(): boolean;
    hasLogoId(onid: any, tsid: any, sid: any): any;
    hasLogo(logo_id: any, onid: any): boolean;
    getTransportStreams(onid: any): {};
    getServices(onid: any, tsid: any): {};
    getOriginalNetworkId(): any;
    getTransportStreamId(): any;
    getServiceIds(): any[];
    getPresent(onid: any, tsid: any, sid: any): any;
    getFollowing(onid: any, tsid: any, sid: any): any;
    getSchedule(): {};
    getScheduleAmount(): number[];
    getTime(): Date;
    getLogoId(onid: any, tsid: any, sid: any): any;
    getLogo(logo_id: any, onid: any): {};
}
import TsEpg = require("./epg");
